# this is a config file for neural network with auxiliary outputs

# input
in_channels: 569

# output
dist_channels: 32
ss_channels: 8
phi_channels: 37
psi_channels: 37

# network params
up_channels: 128
down_channels: 64
RESNET_depth: 200

# other params
crop_size: 64
weights: {'dgram': 10, '2nd': 1, 'phi': 1, 'psi': 1}

X_files: "/faststorage/project/deeply_thinking_potato/data/our_input/tensors/{domain}_X.pt"
Y_files: "/faststorage/project/deeply_thinking_potato/data/our_input/Y_tensors/{domain}_Y.pt"
num_workers: 16
max_epochs: 200
# max_domains: 2000   # 6000 corresponds to approx. 350GB of ram usage
# max_domains: 50
available_domains: "/faststorage/project/deeply_thinking_potato/data/our_input/train_domains.csv"
use_cuda: True
batch_size: 8
model_path: "/faststorage/project/deeply_thinking_potato/data/our_input/model_290420/{epoch}.pt"
log_file: ""
chunk_size: 512
val_size: 32

lr: "1e-3"
# l2: "1e-4"
l2: "0.0"
train_proportion: 0.98  # train=9208 validation=188
seed: 0
